packages:
  - '.'
extra-deps:
  - base-compat-0.9.1
  - base-orphans-0.5.4
compiler: ghcjs-0.2.0_ghc-7.10.2
resolver: ghcjs-0.2.0_ghc-7.10.2

# resolver: ghcjs-0.2.0.20151001_ghc-7.10.2
# compiler-check: match-exact
